version: '2'
services:
  app:
    image: phoenix:1.3.3
    command: sh entrypoint.sh
    build: .
    environment:
      RABBITMQ_HOST: rabbitmq
      DATABASE_HOST: db
    ports:
      - "4000:4000"
    volumes:
      - .:/copan
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres:10
  rabbitmq:
    image: rabbitmq:3.7.7
    environment:
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

